/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pw.proz;

import javax.swing.*;
import java.awt.*;

public class App {

    public static void main(String[] args) {
        JFrame frame = new JFrame("Szachy");
        frame.setSize(700, 700);
        frame.setVisible(true);

        Board board = new Board(frame);

        frame.setLayout(new GridLayout(8,8));
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
}