/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pw.proz;

import Controller.ChessGameController;
import Model.ChessModelBoard;
import View.AppGUI;
import View.ChessViewBoard;

import javax.swing.*;


public class App {
    public static void main(String[] args) {

        JFrame frame = new JFrame("Szachy");

        AppGUI mainFrame = new AppGUI(frame);
        ChessViewBoard chessViewBoardView = new ChessViewBoard(frame.getContentPane());
        ChessModelBoard boardModel = new ChessModelBoard();
        ChessGameController gameController = new ChessGameController(boardModel, chessViewBoardView, mainFrame);

        gameController.initGUI();
        gameController.startNewGame();
    }
}